### ISSUE TITLE
DateTime.utc_now() and Ecto 3

### ISSUE THREAD

**Issue by joshchernoff** [riverrun/phauxth-example#10]
There are a few places that use DateTime.utc_now() 

When upgrading to Ecto 3 you will run into something like. 

```
** (ArgumentError) :utc_datetime expects microseconds to be empty, got: #DateTime<2018-12-29 21:30:01.610809Z>
     
Use `DateTime.truncate(utc_datetime, :second)` (available in Elixir v1.6+) to remove microseconds.
```

as stated the solution is to truncate the seconds, just fyi.

**Comment by riverrun** [comment]
Thanks for pointing that out. I will sort it out during the next week.
