### ISSUE TITLE
No API key set for the Mandrill adapter

### ISSUE THREAD

**Issue by PeterDavidCarter** [riverrun/phauxth-example#2]
When creating a new user, the following error appears:

```
There was no API key set for the Mandrill adapter.
* Here are the config options that were passed in:
%{adapter: Bamboo.MandrillAdapter, api_key: nil}
```

**Comment by riverrun** [comment]
I should add something to the README about this. You need to setup a Mandrill API key yourself - or use a different adapter. You can find more info [here](https://github.com/thoughtbot/bamboo).

**Comment by riverrun** [comment]
I've updated the README, and I've also changed the default config to use the LocalAdapter, instead of the MandrillAdapter.

The LocalAdapter is really good for development.
