### ISSUE TITLE
critique about session destroy

### ISSUE THREAD

**Issue by joshchernoff** [riverrun/phauxth-example#8]
https://github.com/riverrun/phauxth-example/blob/5c722b580676c124d46cfd7ac7d583b005ca8576/lib/forks_the_egg_sample_web/controllers/session_controller.ex#L32-L33

What do you think about only ever being able to destroy a session you own (ie scope the session look ups to the current user vs the session_id. That way you don't even need the session id

maybe something hypothetical like 
```
user_id |> Sessions.get_session_by_user_id() |> Sessions.delete_session()
```

I'm not sure if this would help security wise but I would assume that would be one less vector relying on a http param vs looking up the user supposedly already in a session.

**Comment by joshchernoff** [comment]
my only counter to my own point would be I don't like how it mixes the concern of the user with a session but in a case like this I'm not so sure thats a bad thing.

**Comment by joshchernoff** [comment]
Even better. 
```
 def delete(%Plug.Conn{assigns: %{current_user: current_user }} = conn) do
    case current_user |> Sessions.delete_user_sessions() do
      {:ok} ->
```

**Comment by riverrun** [comment]
Hi. I'm on holiday at the moment, but I will look at this issue when I get back home - on Wednesday.

**Comment by riverrun** [comment]
Fixed in [this commit on March 20](https://github.com/riverrun/phauxth-example/commit/e6757f4aea464b4df28adb0e06e245e41e479575).
