### ISSUE TITLE
Trusting our plug's current_user vs exposing our user's ID. 

### ISSUE THREAD

**Issue by joshchernoff** [riverrun/phauxth-example#9]
So looking at the design around how we are currently checking if a given user is authorized to change their own stuff (ie id_check)

https://github.com/riverrun/phauxth-example/blob/master/lib/forks_the_egg_sample_web/controllers/authorize.ex#L48-L60

Specifically when a given user is editing their out stuff I think there is more value in obscuring the user's id than using it to compare with the current_user in plugs assigns. 

Unless our pipeline has been compromised we should generally be able to trust our plugs assigns.

Thus not requiring a request param id since we have all the info we need in our plugs assign. 

This does change the current pattern to the point where I wonder if the auth plug is even useful in this case anymore since you would likely gate that user in the controller and should in theory never even be able to query a different user than is the one currently in the assigns for current_user. 

All that said that is assuming the context is when you are a normal user editing things only that given user should be able to edit. On the other hand I think it still makes sense from the context of an admin for example where you (current_user) will likely not be the user in question being changed. 

Thoughts?

**Comment by riverrun** [comment]
In this case, I don't want to deviate too much from the 'standard' setup you would expect if you used, for example, phx.gen.html, and I am not sure I see the benefit of it in this case.

I am going to close this issue now, but feel free to comment on this further, and it would be interesting to see if you have used this setup in your own projects.
